
server:
  port: 8080

############# Database Properties ###########################################


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/JWT_back
    username: root
    password:

  # spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
